[来源](http://es6.ruanyifeng.com/#docs/promise)
### 什么是`Promise`
`Promise`是一个容器，里面保存着某个未来才会结束的事件（通常是一个异步操作的结果）

### `Promise`对象的特点
1. 对象的状态不受外接影响。
`Promise`对象代表的异步操作有三种状态：
+ `pending` —— 进行中
+ `fulfilled` —— 已成功
+ `rejected` —— 已失败

2. 状态改变路径
+ `pending` -> `fulfilled`
+ `pending` -> `rejected`
状态改变路径不可逆。
以上两种情况发生，状态就凝固了，此时称为resolved（已定型）


### `Promise`的缺点
1. 无法取消`Promise` —— 一旦创建就会立即执行，无法中途取消
2. 如果不设置回调函数，`Promise`内部抛出的错误，不会反应到外部
3. 当处于`pending`状态时，无法得知目前进展到哪一个阶段

### `Promise`的基本用法
`Promise`是一个构造函数，用来生成`Promise`实例
```js
const promise = new Promise((resolve, reject) => {
    // ... some code

    if (/* 异步操作成功 */){
        resolve(value);
    } else {
        reject(error);
    }
})
```
`resolve`和`reject`两个参数，由`JavaScript`引擎提供，无需自己部署
1. `resolve`函数的作用是：
将`Promise`对象的状态从"未完成"变为"成功"（即从`pending`变为`resolved`），异步操作成功，就将异步操作的结果作为参数`resolve`出去;
2. `reject`函数的作用是：
将`Promise`对象的状态从"未完成"变为"失败"（即从`pending`变为`rejected`），异步操作失败，就将异步操作报出的错误，作为参数`reject`出去

### Promise实例的使用
可以用`then`方法分别指定`resolved`状态和`rejected`状态的回调函数
```js
promise.then(function (value) {

}, function (err) {

});
```
由上可知，`then`方法可以接受两个回调函数作为参数。
+ 第一个回调函数是`Promise`对象的状态变为`resolved`时
+ 第二个回调函数是`Promise`对象的状态变为`rejected`时
Note：第二个参数是可选的，不一定必须提供

`Promise对象新建后，就会立即执行`
```js
let promise = new Promise((resolve, reject) => {
    console.log('Promise');
    resolve();
});

promise.then(function () {
    console.log('resolved');
});

console.log('Hi!');

// Promise
// Hi!
// resolved
```
### `Promise`对象的应用
```js
function loadImageAsync (url) {
    return new Promise(function (resolve, reject) {
        const image = new Image();

        image.load = function () {
            resolve(image);     // 加载成功
        };

        image.onerror = function () {
            reject(new Error('Could not load image at ' + url));
        };

        image.src = url;
    })
}
```

### `Promise`对象实现`Ajax`操作实例
```js
const getJSON = function (url) {
    const promise = new Promise(function (resolve, reject) {
        const handler = function () {
            if (this.readyState !== 4) {
                return;
            }

            if (this.status === 200) {
                resolve(this.response);
            } else {
                reject(new Error(this.statusTex));
            }
        };

        const client = new XMLHttpRequest();
        client.open("GET", url);
        client.onreadystatechange = handler;
        client.responseType = "json";
        client.setRequestHeader("Accept", "application/json");
        client.send();
    });

    return promise;
};

getJSON("/posts.json").then(function (json) {
    console.log('Contents: ' + json);
}, function (error) {
    console.error('出错了', error);
});
```

`resolve`函数的参数除了正常的值外，还可能是另一个`Promise`实例
```js
// 例如
const p1 = new Promise(function (resolve, reject) {
  // ...
});

const p2 = new Promise(function (resolve, reject) {
  // ...
  resolve(p1);
})
```
上述代码，`p1`和`p2`都是`Promise`实例，`p2`的`resolve`方法将`p1`作为参数，即一个异步操作的结果是返回另一个异步操作

`p1`的状态决定了`p2`的状态，`p1`的状态是`pending`，`p2`的回调函数就会等待`p1`的状态改变；若`p1`的状态已经是`resolved`或`rejected`，则`p2`的回调函数会立即执行

```js
const p1 = new Promise(function (resolve, reject) {
  setTimeout(() => reject(new Error('fail')), 3000)
})

const p2 = new Promise(function (resolve, reject) {
  setTimeout(() => resolve(p1), 1000)
})

p2
  .then(result => console.log(result))
  .catch(error => console.log(error))
// Error: fail
```
上面代码中，`p1`是一个 `Promise`，3 秒之后变为`rejected`。`p2`的状态在 1 秒之后改变，`resolve`方法返回的是`p1`。由于`p2`返回的是另一个 `Promise`，导致`p2`自己的状态无效了，由`p1`的状态决定`p2`的状态。所以，后面的then语句都变成针对后者（`p1`）。又过了 2 秒，`p1`变为`rejected`，导致触发`catch`方法指定的回调函数。

调用`resolve`或`reject`并不会终结 `Promise` 的参数函数的执行。
```js
new Promise((resolve, reject) => {
  resolve(1);
  console.log(2);
}).then(r => {
  console.log(r);
});
// 2
// 1
```